let shopItemsData = [
    {
        id: "a",
        name: "Nome1",
        price: 45,
        desc: "Descrição 1",
        img: "images/face.jpg",
    },
    {
        id: "b",
        name: "Nome2",
        price: 45,
        desc: "Descrição 2",
        img: "images/copa 2.jpg",
    },
    {
        id: "c",
        name: "Nome3",
        price: 45,
        desc: "Descrição 3",
        img: "images/copa 8.jpg",
    },
    {
        id: "d",
        name: "Nome4",
        price: 45,
        desc: "Descrição 4",
        img: "images/copa 4.jpg",
    },
    {
        id: "e",
        name: "Nome5",
        price: 45,
        desc: "Descrição 5",
        img: "images/copa 5.jpg",
    },
    {
        id: "f",
        name: "Nome6",
        price: 45,
        desc: "Descrição 6",
        img: "images/copa 6.jpg",
    },
    {
        id: "g",
        name: "Nome7",
        price: 45,
        desc: "Descrição 7",
        img: "images/copa 12.jpg",
    },
    {
        id: "h",
        name: "Nome8",
        price: 45,
        desc: "Descrição 8",
        img: "images/copa 8.jpg",
    },
    {
        id: "i",
        name: "Nome9",
        price: 45,
        desc: "Descrição 9",
        img: "images/copa 9.jpg",
    },
    {
        id: "j",
        name: "Nome10",
        price: 45,
        desc: "Descrição 10",
        img: "images/copa.jpg",
    },
    {
        id: "k",
        name: "Nome11",
        price: 45,
        desc: "Descrição 11",
        img: "images/copa 13.jpg",
    },
    {
        id: "l",
        name: "Nome12",
        price: 45,
        desc: "Descrição 12",
        img: "images/Guest.jpg",
    },
];